fail_fast: true
repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.3"
    hooks:
      - id: poetry-check

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        types: [python]
        args: [--fix]
      - id: ruff-format
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "pandas-stubs"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
